GET http://localhost:3000/books HTTP/1.1

###

GET http://localhost:3000/books/2 HTTP/1.1

###

POST http://localhost:3000/books HTTP/1.1
Content-Type:  application/json

    {
        "title": "mi nueBo libro",
        "author": "vos sos tu propio autor",
        "year": 2030
    }

###
PUT http://localhost:3000/books/3 HTTP/1.1
Content-Type: application/json

{
  "title":"estoy cansado jefe" ,
  "author":"By ChatGPT" ,
  "year": 2031
}

###

DELETE http://localhost:3000/books/3 HTTP/1.1